### ISSUE TITLE
Text Misaligned In Directory Section Headers

### ISSUE THREAD

**Issue by GJTaser** [cutonbuminband/rcounting#2]
Hello, this is ProductionsGJT from r/counting - I decided to create an issue on here since I also have an account on GitHub. :)

I'm not sure how long this has been the case, but the update script seems to be generating severely misaligned text in the section headers of the side thread directory:
![Directory Section Header Misalignment](https://github.com/cutonbuminband/rcounting/assets/66844111/3f51e128-d011-4c60-9efa-33600e073325)

I first tried to fix this by manually editing the header spacing on the wiki page, but the update script automatically reverts any manual changes made to the headers (hence the reason for going the GitHub route). This leaves me with two questions:
1. Can you confirm that the misalignment is not just a product of the browser (Google Chrome) I am using?
2. Is this something that tweaking the update script can fix?

Thanks in advance for taking the time to work on this issue. :)

**Comment by cutonbuminband** [comment]
I can confirm that it's not just an issue with Chrome, so thanks for catching that. I think reddit changed how they show the side bar on that page so there's less horizontal space available.

The header is defined [here](https://github.com/cutonbuminband/rcounting/blob/5ee9d8f311f013d37223630e44f2ec40f58f67ae/rcounting/thread_directory.py#L260C27-L260C27), and updating it shouldn't be any problem.

Do you know what would be the right amount of spaces?

**Comment by cutonbuminband** [comment]
Oops, I didn't mean to close the issue

**Comment by GJTaser** [comment]
Let me do some test editing, and I'll get back to you on it...

EDIT: After testing, I've realized that the width of the tables don't "stretch" if you add more padding spaces to the header - they'll stay at the width of the longest entry in each column of the table and only stretch across the screen if that longest entry wraps across more than one line. So you will either need to A. Put the "padding spaces" around the "Current Thread" entries to force the stretch and/or B. Center align all the tables.

For right now, I will just set all spacings in the header text to 1 on each side to try to keep the text centered. But I don't think fiddling with the header spacings will fix the formatting problem...

**Comment by cutonbuminband** [comment]
I'm travelling right now and can't easily check, but it used to be that regular spaces behave as you describe, but other blank characters didn't. That's why the header has 0x2800, "Braille pattern blank" instead of spaces.

Getting the tables to full width on the page is important, and for me more important than having a perfectly aligned header

**Comment by GJTaser** [comment]
Understood. I'll try again using the special character...

EDIT: OK, after some more experimenting I found that using 6 instead of 10 of the special blank characters for the first two sections and 1 instead of 3 for the third one fixes **most** of the formatting issues (some columns are so narrow that it'll be easier to make the text deliberately wrap to two lines). It doesn't quite reach all the way across the page though, so more tweaking may be required. The 6-6-1 pattern is at least a good starting point, though.

**Comment by GJTaser** [comment]
Nope, 7-7-2 still has the wonky formatting. What was wrong with the 6-6-1 pattern?

**Comment by cutonbuminband** [comment]
Went down to 661 now. I was being lazy, and testing things by running the script as normal to confirm that there was still an issue

**Comment by GJTaser** [comment]
Yeah, that definitely looks better. Some stuff still looks out of whack formatting wise, but since you prioritize having it at full width that would require a different approach to fix. I'll close this for now, and if it gets really bad again it can be reopened at a later date.
